name: Deploy Flutter Canvas to GH Pages

on:
  push:
    branches:
      - main # Apnar branch jodi 'master' hoy tobe 'master' likhun

permissions:
  contents: write # Eti khub-i dorkari deploy korar jonno

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter pub get

      # Build step (base-href thik ache)
      - run: flutter build web --release --base-href "/flutter_canvas/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          publish_branch: gh-pages # Explicitly branch-ti bole dewa bhalo